blank_issues_enabled: true

contact_links:
  - name: balena forums
    url: https://forums.balena.io
    about: Please ask your technical questions here.
  - name: balena contact
    url: https://www.balena.io/contact/
    about: Get in touch with us.
